-- Production / fresh-environment setup
-- Run AFTER db:migrate (drizzle creates the tables first).
--
-- Execution order for a fresh environment:
--   1. npm run db:migrate            (creates the schema + tables)
--   2. psql -f supabase/seed.sql     (lookup seed data — REQUIRED before step 3
--                                     if you enable the reverse-trial trigger:
--                                     it RAISEs without the seeded subscription
--                                     tiers; the quota framework also needs the
--                                     'free' tier + its quota row)
--   3. psql -f supabase/prod-setup.sql  (this file — grants, trigger, FKs, RLS, CHECKs, updated_at)
--
-- This file contains Supabase-specific constructs that Drizzle ORM cannot manage:
--   1. Schema grants for anon / authenticated / service_role roles
--   2. Auth trigger (auto-create a user_preferences row on signup)
--   3. Cross-schema foreign keys (vt_saas.* -> auth.users)
--   4. Row-Level Security policies
--   5. CHECK constraints on text-typed enum columns (one illustrative example)
--   6. Generic updated_at trigger (set_updated_at, auto-attached per table)
--
-- Safe to re-run: every block uses CREATE OR REPLACE, IF NOT EXISTS, or DROP ... IF EXISTS.
--
-- SCHEMA NAME: this file assumes the DB_SCHEMA default `vt_saas` (see .env.example /
-- src/models/Schema.ts). If you set a different DB_SCHEMA, replace `vt_saas` throughout.
-- For a dedicated Supabase instance you may use `public` — in that case grants are
-- mostly redundant (Supabase auto-grants public) but the trigger / FKs / RLS still apply.
--
-- See docs/database-workflow.md for the three-home model and .claude/rules/database.md
-- for the must-not-break rules.

-- ============================================================
-- 1. SCHEMA GRANTS
-- ============================================================
-- Supabase only auto-grants on the public schema. A custom schema (created by
-- drizzle migration 0000 via CREATE SCHEMA) needs explicit grants, or the
-- Supabase JS client gets "permission denied" on every query.
-- service_role is required by admin clients (server-side jobs, admin APIs)
-- which bypass RLS for trusted operations.

GRANT USAGE ON SCHEMA vt_saas TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA vt_saas TO authenticated, service_role;
GRANT SELECT ON ALL TABLES IN SCHEMA vt_saas TO anon;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA vt_saas TO authenticated, service_role;

-- Ensure future tables also get grants
ALTER DEFAULT PRIVILEGES IN SCHEMA vt_saas GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA vt_saas GRANT SELECT ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA vt_saas GRANT USAGE ON SEQUENCES TO authenticated, service_role;

-- ============================================================
-- 2. AUTH TRIGGER
-- ============================================================
-- Auto-create a user_preferences row whenever a new auth.users row is inserted.
-- user_preferences uses a separate `id` PK with a UNIQUE `user_id` (see
-- src/models/Schema.ts), so the trigger keys the row on user_id — `id` is
-- generated by the column default, and display_name / username stay NULL.
--
-- NAMESPACING: trigger names on auth.users share ONE namespace across every
-- project on a Supabase instance, and functions live in a schema. On a shared
-- dev instance hosting several forks, a fixed name like `on_auth_user_created`
-- + `public.handle_new_user()` means the last fork to run this file hijacks
-- every other fork's signup trigger. So the trigger name is prefixed with the
-- schema and the function lives IN the schema — the /init-downstream rename
-- sweep then namespaces both automatically, and forks coexist safely.

-- Legacy cleanup: earlier template versions used the un-namespaced names.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

CREATE OR REPLACE FUNCTION vt_saas.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO "vt_saas"."user_preferences" (user_id, created_at, updated_at)
  VALUES (NEW.id, NOW(), NOW())
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS vt_saas_on_auth_user_created ON auth.users;
CREATE TRIGGER vt_saas_on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION vt_saas.handle_new_user();

-- ---- subscription enrollment (one row per user) ----
-- Auto-create a user_subscriptions row on signup so the quota framework always
-- finds one. REQUIRES supabase/seed.sql to have inserted the subscription tiers
-- first (this function RAISEs otherwise). Two coexisting AFTER INSERT triggers on
-- auth.users (this + vt_saas_on_auth_user_created above) is fine.
--
-- DEFAULT (safe-by-default): enroll every new user on the FREE tier — no trial,
-- no card. This is what ships uncommented.

-- Legacy cleanup: earlier template versions used the un-namespaced names.
DROP TRIGGER IF EXISTS on_auth_user_created_subscription ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user_subscription();

CREATE OR REPLACE FUNCTION vt_saas.handle_new_user_subscription()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  free_tier_id uuid;
BEGIN
  SELECT id INTO free_tier_id FROM "vt_saas"."subscription_tiers" WHERE name = 'free';
  IF free_tier_id IS NULL THEN
    RAISE EXCEPTION 'handle_new_user_subscription: free tier not seeded (run supabase/seed.sql first)';
  END IF;

  INSERT INTO "vt_saas"."user_subscriptions" (user_id, tier_id, status, started_at, current_period_anchor_at, created_at, updated_at)
  VALUES (NEW.id, free_tier_id, 'active', NOW(), NOW(), NOW(), NOW())
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS vt_saas_on_auth_user_created_subscription ON auth.users;
CREATE TRIGGER vt_saas_on_auth_user_created_subscription
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION vt_saas.handle_new_user_subscription();

-- ---- OPT-IN reverse-trial variant ----
-- To enroll every new user in an N-day trial on the PRO tier (no card),
-- REPLACE the function body above with the version below, then re-run this file.
-- This changes product behaviour (every signup gets Pro for free), so it is
-- opt-in and ships commented out.
--
-- ⚠️ DUAL-SOURCE CAVEAT: the trial length lives in TWO places — the
-- `INTERVAL '14 days'` literal below AND the TS `TRIAL_DAYS` env var (which gates
-- the expiry crons). Keep them in sync. Also flip `ENABLE_REVERSE_TRIAL=true` so
-- the force-expire + expiry-warning crons run. See docs/subscriptions.md.
--
-- CREATE OR REPLACE FUNCTION vt_saas.handle_new_user_subscription()
-- RETURNS TRIGGER
-- LANGUAGE plpgsql
-- SECURITY DEFINER SET search_path = ''
-- AS $$
-- DECLARE
--   pro_tier_id uuid;
-- BEGIN
--   SELECT id INTO pro_tier_id FROM "vt_saas"."subscription_tiers" WHERE name = 'pro';
--   IF pro_tier_id IS NULL THEN
--     RAISE EXCEPTION 'handle_new_user_subscription: pro tier not seeded (run supabase/seed.sql first)';
--   END IF;
--
--   INSERT INTO "vt_saas"."user_subscriptions"
--     (user_id, tier_id, status, has_trialed, trial_expires_at, started_at, current_period_anchor_at, created_at, updated_at)
--   VALUES
--     (NEW.id, pro_tier_id, 'trial', true, NOW() + INTERVAL '14 days', NOW(), NOW(), NOW(), NOW())  -- set 14 to TRIAL_DAYS
--   ON CONFLICT (user_id) DO NOTHING;
--   RETURN NEW;
-- END;
-- $$;

-- ============================================================
-- 3. CROSS-SCHEMA FOREIGN KEYS
-- ============================================================
-- Drizzle cannot generate cross-schema FKs — it has no model of the `auth`
-- namespace. These ensure cascade behaviour when a user is removed from
-- auth.users. The DO $$ ... IF NOT EXISTS ... END $$; wrapper makes each block
-- idempotent (re-running is a no-op once the constraint exists).
--
-- Add one block per user-owned table you introduce, keyed on its user column.

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_user_preferences_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."user_preferences"
      ADD CONSTRAINT fk_user_preferences_auth_users
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_threads_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."threads"
      ADD CONSTRAINT fk_threads_auth_users
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_shareable_links_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."shareable_links"
      ADD CONSTRAINT fk_shareable_links_auth_users
      FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- admin_audit_log: admin_id cascades; target_id uses SET NULL so the audit
-- trail survives when the targeted user is deleted. (target_id is NOT NULL in
-- the schema today; if you keep SET NULL, also DROP NOT NULL on target_id.)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_admin_audit_log_admin_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."admin_audit_log"
      ADD CONSTRAINT fk_admin_audit_log_admin_auth_users
      FOREIGN KEY (admin_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_admin_audit_log_target_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."admin_audit_log"
      ALTER COLUMN target_id DROP NOT NULL;
    ALTER TABLE "vt_saas"."admin_audit_log"
      ADD CONSTRAINT fk_admin_audit_log_target_auth_users
      FOREIGN KEY (target_id) REFERENCES auth.users(id) ON DELETE SET NULL;
  END IF;
END $$;

-- feedback: SET NULL preserves anonymous + submitted-then-deleted feedback.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_feedback_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."feedback"
      ADD CONSTRAINT fk_feedback_auth_users
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
  END IF;
END $$;

-- vercel_conversations: user-owned AI chat history. CASCADE so a deleted user's
-- conversations (and, via the intra-schema FK below, their messages) are removed.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_vercel_conversations_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."vercel_conversations"
      ADD CONSTRAINT fk_vercel_conversations_auth_users
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- mem0_memories: user-owned extracted facts/preferences (PII). CASCADE so a
-- deleted user's memory rows don't linger (right-to-erasure hygiene).
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_mem0_memories_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."mem0_memories"
      ADD CONSTRAINT fk_mem0_memories_auth_users
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- platform_connections: user-owned third-party OAuth credentials (encrypted
-- tokens). CASCADE so deleting a user erases their stored credentials, same
-- rationale as mem0_memories.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_platform_connections_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."platform_connections"
      ADD CONSTRAINT fk_platform_connections_auth_users
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- scheduled_tasks: server-only background-job queue. CASCADE so a deleted
-- user's pending/finished tasks don't linger.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_scheduled_tasks_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."scheduled_tasks"
      ADD CONSTRAINT fk_scheduled_tasks_auth_users
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- user_subscriptions: one row per user. CASCADE so a deleted user's subscription
-- row is removed. (tier_id -> subscription_tiers is an intra-schema FK Drizzle
-- already created in the migration.)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_user_subscriptions_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."user_subscriptions"
      ADD CONSTRAINT fk_user_subscriptions_auth_users
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- resource_usage: per-user usage ledger. CASCADE so a deleted user's usage rows
-- don't linger.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'fk_resource_usage_auth_users'
  ) THEN
    ALTER TABLE "vt_saas"."resource_usage"
      ADD CONSTRAINT fk_resource_usage_auth_users
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- ============================================================
-- 4. ROW-LEVEL SECURITY
-- ============================================================
-- Convention:
--   - User-owned tables: users can only access their own rows (auth.uid() = user_id)
--   - Lookup tables: read-only for authenticated (see the variant at the bottom)
--   - System / server-only tables (admin_audit_log, the *_jobs / message tables):
--     no policy = no client access (service role bypasses RLS)
-- Idiom: ENABLE ROW LEVEL SECURITY + DROP POLICY IF EXISTS + CREATE POLICY, so re-runs are safe.
--
-- ⚠️ DENY-BY-DEFAULT IS MANDATORY. The schema grants above hand `anon` SELECT and
-- `authenticated` full CRUD on EVERY table, and supabase/config.toml exposes the
-- whole schema over the REST API. RLS is the only thing standing between that and
-- a public data leak. Therefore: **enable RLS on EVERY table in the schema** — a
-- table with RLS ON and no matching policy denies all non-service-role access, so
-- forgetting a policy fails closed, not open. A table that is REST-exposed and
-- granted but has RLS OFF leaks every user's rows to anyone with the public anon
-- key. When you add a table, add an `ALTER TABLE ... ENABLE ROW LEVEL SECURITY`
-- line here in the same change.

-- ---- user_preferences ----
-- No INSERT policy: rows are created by the handle_new_user trigger above.
ALTER TABLE "vt_saas"."user_preferences" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "user_preferences_select_own" ON "vt_saas"."user_preferences";
CREATE POLICY "user_preferences_select_own" ON "vt_saas"."user_preferences"
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "user_preferences_update_own" ON "vt_saas"."user_preferences";
CREATE POLICY "user_preferences_update_own" ON "vt_saas"."user_preferences"
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ---- threads ----
ALTER TABLE "vt_saas"."threads" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "threads_select_own" ON "vt_saas"."threads";
CREATE POLICY "threads_select_own" ON "vt_saas"."threads"
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "threads_insert_own" ON "vt_saas"."threads";
CREATE POLICY "threads_insert_own" ON "vt_saas"."threads"
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "threads_update_own" ON "vt_saas"."threads";
CREATE POLICY "threads_update_own" ON "vt_saas"."threads"
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "threads_delete_own" ON "vt_saas"."threads";
CREATE POLICY "threads_delete_own" ON "vt_saas"."threads"
  FOR DELETE USING (auth.uid() = user_id);

-- ---- shareable_links ----
-- Owner column is created_by, not user_id.
ALTER TABLE "vt_saas"."shareable_links" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "shareable_links_select_own" ON "vt_saas"."shareable_links";
CREATE POLICY "shareable_links_select_own" ON "vt_saas"."shareable_links"
  FOR SELECT USING (auth.uid() = created_by);
DROP POLICY IF EXISTS "shareable_links_insert_own" ON "vt_saas"."shareable_links";
CREATE POLICY "shareable_links_insert_own" ON "vt_saas"."shareable_links"
  FOR INSERT WITH CHECK (auth.uid() = created_by);
DROP POLICY IF EXISTS "shareable_links_delete_own" ON "vt_saas"."shareable_links";
CREATE POLICY "shareable_links_delete_own" ON "vt_saas"."shareable_links"
  FOR DELETE USING (auth.uid() = created_by);

-- ---- feedback ----
-- Users insert + read their own; anonymous feedback (user_id IS NULL) is service-role only.
ALTER TABLE "vt_saas"."feedback" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "feedback_select_own" ON "vt_saas"."feedback";
CREATE POLICY "feedback_select_own" ON "vt_saas"."feedback"
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "feedback_insert_own" ON "vt_saas"."feedback";
CREATE POLICY "feedback_insert_own" ON "vt_saas"."feedback"
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ---- admin_audit_log ----
-- No client access: service role only. Enabling RLS with no policy denies all
-- non-service-role access (service_role bypasses RLS).
ALTER TABLE "vt_saas"."admin_audit_log" ENABLE ROW LEVEL SECURITY;
-- (intentionally no CREATE POLICY)

-- ---- vercel_conversations ----
-- User-owned AI chat history. Has a direct user_id, so scope rows to the owner.
ALTER TABLE "vt_saas"."vercel_conversations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "vercel_conversations_select_own" ON "vt_saas"."vercel_conversations";
CREATE POLICY "vercel_conversations_select_own" ON "vt_saas"."vercel_conversations"
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "vercel_conversations_insert_own" ON "vt_saas"."vercel_conversations";
CREATE POLICY "vercel_conversations_insert_own" ON "vt_saas"."vercel_conversations"
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "vercel_conversations_update_own" ON "vt_saas"."vercel_conversations";
CREATE POLICY "vercel_conversations_update_own" ON "vt_saas"."vercel_conversations"
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "vercel_conversations_delete_own" ON "vt_saas"."vercel_conversations";
CREATE POLICY "vercel_conversations_delete_own" ON "vt_saas"."vercel_conversations"
  FOR DELETE USING (auth.uid() = user_id);

-- ---- mem0_memories ----
-- User-owned extracted facts/preferences. Direct user_id → scope to the owner.
ALTER TABLE "vt_saas"."mem0_memories" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "mem0_memories_select_own" ON "vt_saas"."mem0_memories";
CREATE POLICY "mem0_memories_select_own" ON "vt_saas"."mem0_memories"
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "mem0_memories_insert_own" ON "vt_saas"."mem0_memories";
CREATE POLICY "mem0_memories_insert_own" ON "vt_saas"."mem0_memories"
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "mem0_memories_update_own" ON "vt_saas"."mem0_memories";
CREATE POLICY "mem0_memories_update_own" ON "vt_saas"."mem0_memories"
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "mem0_memories_delete_own" ON "vt_saas"."mem0_memories";
CREATE POLICY "mem0_memories_delete_own" ON "vt_saas"."mem0_memories"
  FOR DELETE USING (auth.uid() = user_id);

-- ---- platform_connections ----
-- User-owned third-party OAuth credentials. Direct user_id → scope to the owner.
-- DB-layer RLS here is defense in depth alongside the app-layer safe fetcher
-- (get-platform-connections.ts) that excludes the encrypted token columns.
ALTER TABLE "vt_saas"."platform_connections" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "platform_connections_select_own" ON "vt_saas"."platform_connections";
CREATE POLICY "platform_connections_select_own" ON "vt_saas"."platform_connections"
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "platform_connections_insert_own" ON "vt_saas"."platform_connections";
CREATE POLICY "platform_connections_insert_own" ON "vt_saas"."platform_connections"
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "platform_connections_update_own" ON "vt_saas"."platform_connections";
CREATE POLICY "platform_connections_update_own" ON "vt_saas"."platform_connections"
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "platform_connections_delete_own" ON "vt_saas"."platform_connections";
CREATE POLICY "platform_connections_delete_own" ON "vt_saas"."platform_connections"
  FOR DELETE USING (auth.uid() = user_id);

-- ---- vercel_messages ----
-- Server-only: rows are scoped to a parent conversation (no direct user_id) and
-- are only ever read/written by trusted server code (Drizzle over DATABASE_URL,
-- which bypasses RLS). RLS ON + no policy denies all anon/authenticated REST
-- access. (To expose to clients later, add a policy joining to vercel_conversations.)
ALTER TABLE "vt_saas"."vercel_messages" ENABLE ROW LEVEL SECURITY;
-- (intentionally no CREATE POLICY — server-only)

-- ---- memory_extraction_jobs ----
-- Server-only async job queue. No client access; same rationale as vercel_messages.
ALTER TABLE "vt_saas"."memory_extraction_jobs" ENABLE ROW LEVEL SECURITY;
-- (intentionally no CREATE POLICY — server-only)

-- ---- scheduled_tasks ----
-- Server-only background-job queue: written only by the cron + admin client.
-- RLS ON + no policy denies all anon/authenticated REST access (service role
-- bypasses RLS); same rationale as memory_extraction_jobs / vercel_messages.
ALTER TABLE "vt_saas"."scheduled_tasks" ENABLE ROW LEVEL SECURITY;
-- (intentionally no CREATE POLICY — server-only)

-- ---- subscription_tiers ----
-- Lookup/catalogue table every signed-in user may read but not write (the
-- pricing grid + quota resolver read it). Writes are server-only.
ALTER TABLE "vt_saas"."subscription_tiers" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "subscription_tiers_select_authenticated" ON "vt_saas"."subscription_tiers";
CREATE POLICY "subscription_tiers_select_authenticated" ON "vt_saas"."subscription_tiers"
  FOR SELECT USING (auth.role() = 'authenticated');

-- ---- tier_quotas ----
-- Lookup table (per-tier quota config). Same read-only-for-authenticated rule.
ALTER TABLE "vt_saas"."tier_quotas" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tier_quotas_select_authenticated" ON "vt_saas"."tier_quotas";
CREATE POLICY "tier_quotas_select_authenticated" ON "vt_saas"."tier_quotas"
  FOR SELECT USING (auth.role() = 'authenticated');

-- ---- user_subscriptions ----
-- Users read their own row. No INSERT/UPDATE policy: rows are created by the
-- signup trigger above and only ever mutated by server code (the Stripe webhook,
-- the expiry crons, the lazy-expiry path) via the service role.
ALTER TABLE "vt_saas"."user_subscriptions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "user_subscriptions_select_own" ON "vt_saas"."user_subscriptions";
CREATE POLICY "user_subscriptions_select_own" ON "vt_saas"."user_subscriptions"
  FOR SELECT USING (auth.uid() = user_id);

-- ---- resource_usage ----
-- Server-only usage ledger: recorded by trusted server code only. RLS ON + no
-- policy denies all anon/authenticated REST access (service role bypasses RLS).
ALTER TABLE "vt_saas"."resource_usage" ENABLE ROW LEVEL SECURITY;
-- (intentionally no CREATE POLICY — server-only)

-- ---- stripe_webhook_events ----
-- Server-only Stripe webhook idempotency ledger: written only by the webhook
-- handler. RLS ON + no policy denies all anon/authenticated REST access (service
-- role bypasses RLS).
ALTER TABLE "vt_saas"."stripe_webhook_events" ENABLE ROW LEVEL SECURITY;
-- (intentionally no CREATE POLICY — server-only)

-- Variant — authenticated read-only lookup table (uncomment + adapt for a
-- reference table every signed-in user may read but not write — see the
-- subscription_tiers / tier_quotas blocks above for a live example):
-- ALTER TABLE "vt_saas"."<lookup_table>" ENABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS "<lookup_table>_select_authenticated" ON "vt_saas"."<lookup_table>";
-- CREATE POLICY "<lookup_table>_select_authenticated" ON "vt_saas"."<lookup_table>"
--   FOR SELECT USING (auth.role() = 'authenticated');

-- ============================================================
-- 5. CHECK CONSTRAINTS (text-typed enum guards)
-- ============================================================
-- When a column stores an enum as plain `text` (TS-side $type<...> only), there
-- is no DB-level guard against bad writes. Add a CHECK so the database enforces
-- it in every environment. Wrap in the same idempotent DO $$ IF NOT EXISTS idiom.
--
-- PATTERN (documentation only — intentionally NOT executed here). The template's
-- own enum columns (e.g. feedback.status) are real pg enums, so a CHECK would be
-- both redundant AND a trap: a CHECK that hard-codes the allowed values silently
-- rejects every write using a value added later via `ALTER TYPE ... ADD VALUE`.
-- Only add a CHECK for a column typed as plain `text` (no pg enum behind it).
-- Copy this block, drop the leading `-- `, and swap in your own table/column:
--
-- DO $$ BEGIN
--   IF NOT EXISTS (
--     SELECT 1 FROM information_schema.table_constraints
--     WHERE constraint_schema = 'vt_saas' AND constraint_name = 'my_status_check'
--   ) THEN
--     ALTER TABLE "vt_saas"."my_table"
--       ADD CONSTRAINT my_status_check
--       CHECK (my_status IN ('pending', 'reviewed', 'archived'));
--   END IF;
-- END $$;

-- LIVE EXAMPLE: user_subscriptions.status and .billing_interval are text columns
-- with TS-side $type<> unions only (NOT pg enums — see
-- src/models/schema/user-subscriptions.ts), so the DB needs CHECKs to enforce them.
-- Keep the value lists in sync with userSubscriptionStatusEnum / billingIntervalEnum.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'user_subscriptions_status_check'
  ) THEN
    ALTER TABLE "vt_saas"."user_subscriptions"
      ADD CONSTRAINT user_subscriptions_status_check
      CHECK (status IN ('active', 'trial', 'expired', 'cancelled'));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'vt_saas' AND constraint_name = 'user_subscriptions_billing_interval_check'
  ) THEN
    ALTER TABLE "vt_saas"."user_subscriptions"
      ADD CONSTRAINT user_subscriptions_billing_interval_check
      CHECK (billing_interval IS NULL OR billing_interval IN ('monthly', 'yearly'));
  END IF;
END $$;

-- ============================================================
-- 6. UPDATED_AT TRIGGER
-- ============================================================
-- One generic function attached to EVERY table in the schema that has an
-- `updated_at` column. Self-maintaining: re-running this block picks up any
-- newly added table automatically. App code may still set updated_at; the
-- trigger always overrides it with the DB clock (NOW()), the more correct value.

CREATE OR REPLACE FUNCTION vt_saas.set_updated_at() RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END $$;

-- The loop below queries information_schema and EXECUTEs dynamic SQL, so the
-- schema name lives in a single variable rather than hard-coded literals inside
-- format() strings. If you set a different DB_SCHEMA, change `schema_name` here
-- (and move set_updated_at into that schema) — not scattered string fragments.
DO $$
DECLARE
  schema_name text := 'vt_saas';
  r record;
BEGIN
  FOR r IN
    SELECT table_name FROM information_schema.columns
    WHERE table_schema = schema_name AND column_name = 'updated_at'
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I.%I', r.table_name, schema_name, r.table_name);
    EXECUTE format(
      'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I.%I '
      || 'FOR EACH ROW EXECUTE FUNCTION %I.set_updated_at()',
      r.table_name, schema_name, r.table_name, schema_name
    );
  END LOOP;
END $$;
