// Generated by `npm run db:gen-types` from the live database.
//
// This committed stub is a generic placeholder so `db-types.ts` type-checks out of
// the box. Run `npm run db:gen-types` (after setting `DB_SCHEMA` and the project id)
// to overwrite it with your product's real schema — and regenerate after every
// migration so a dropped column becomes a `tsc` error instead of a prod 400.

export type Json
  = | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '13.0.5';
  };
  public: {
    Tables: Record<never, never>;
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};
